[workspace]
members = [
    "ui-rs/crates/mines_uirs",
    "ui-rs/crates/mines_mogwai",
]

[profile.release]
# This makes the compiled code faster and smaller, but it makes compiling slower,
# so it's only enabled in release mode.
lto = true
opt-level = 's'
