version: '3'
services:
  db:
    image: postgres:13.1
    container_name: db01
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mines_db
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data/

  api:
    container_name: api
    build:
      dockerfile: Api.Dockerfile
      context: .
    ports:
      - '3000:3000'
    env_file: ./server-nest/.env
    environment:
      - PORT=3000

  ui:
    container_name: ui
    build:
      dockerfile: Ui.Dockerfile
      context: .
      args:
        - api_base_url=http://api:3000
    ports:
      - '4000:3000'
    env_file: ./ui/.env
    depends_on:
      - api

volumes:
  pg_data:

networks:
  default:
    driver: bridge
