name: Generate Mutants
on: # Keep the job but don't run it for anything
jobs:
  generate_mutants_api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        task: ['exec stryker run']
    steps:
      - uses: actions/checkout@v1
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache node_modules for yarn
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-node${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-node${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
            ${{ runner.os }}-yarn-node${{ matrix.node-version }}-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and ${{ matrix.task }}
        run: |
          yarn install
          yarn workspace @mines/nest ${{ matrix.task }}
        env:
          CI: true
          JWT_SECRET: 'a value for tests'
          STRYKER_DASHBOARD_API_KEY: '${{ secrets.STRYKER_DASHBOARD_API_KEY }}'
